# Generated by Django 5.1.7 on 2025-03-31 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('AA', 'Addis Ababa'), ('AF', 'Afar'), ('AM', 'Amhara'), ('BG', 'Benishangul-Gumuz'), ('DR', 'Dire Dawa'), ('GB', 'Gambela'), ('HR', 'Harari'), ('OR', 'Oromia'), ('SM', 'Somali'), ('SE', 'South Ethiopia'), ('SER', 'Southwest Ethiopia Peoples Region'), ('TR', 'Tigray')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
